# see the following for documentation of these options
# http://bedrock.readthedocs.io/en/latest/pipeline.html#configuration
require_tag: true
regions:
  - oregon-b
  - frankfurt
  - iowa-a
apps:
  - bedrock-prod
integration_tests:
  oregon-b:
    - chrome
    - download
    - firefox
    - headless
    - ie
    - ie8
  frankfurt:
    - headless
  iowa-a:
    - headless
